AddonId: 8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2
Packages:
  - Version: 1.6
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-10-19
    PackageUrl: https://github.com/XenorPLxx/Helium-Enhanced-Grid-Mod/releases/download/1.6/8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2_1_6.pthm
    Changelog:
      - "Forked from Helium by darklinkpower"
      - "Modified Grid view to better utilize displays with higher horizontal pixel count"
